# ubuntu 22.04 網路設定範本
network:
  version: 2
  ethernets:
    enp0s3:
      dhcp4: true
    enp0s8:
      dhcp4: false
      addresses: [10.13.10.52/24]
      routes:
        - to: default
          via: 10.13.10.255
      nameservers:
        addresses: [1.1.1.1,8.8.8.8]